### ISSUE TITLE
B#10-Sign up | Upon success Signup user is not being redirected as a logged in user

### ISSUE THREAD

**Issue by horizonvert1027** [success-together/Booing-frontend#11]
-Current Behavior:
Notice that after every success signup, after verification code matched, the user needs to logged in again instead of being redirected as a logged in user.

-App Version:
Booing version 2

-Device Tested:
• Samsung Galaxy A12, Android v12
• Samsung Galaxy A11, Android v12

-Steps to Reproduce:
Precondition: The user has finished the signup process until recieving the verification code.
1. Input the verification code received in the email.
2. Tap Verify and observe.
3. Verify that after verification matches, the user will be redirected to the Login page instead of being redirected as an already logged in user.

-Expected Result:
After verification code matched, the user should be redirected as logged in user, instead of logging in again after success signup.

**Comment by success-together** [comment]
It's fixed already in new version.
