### ISSUE TITLE
B#11-Sign up | Form field is not marked as required

### ISSUE THREAD

**Issue by horizonvert1027** [success-together/Booing-frontend#12]
-Current Behavior:
Notice that the form fields is not marked as required. After tapping the Signup button, there is no flag notification that the field is required but the user is not able to proceed to the next step.

-App Version:
Booing version 2

-Device Tested:
• Samsung Galaxy A12, Android v12
• Samsung Galaxy A11, Android v12

-Steps to Reproduce:
1. Tap Signup and observe.
2. Verify that there is no flag notification that fields required input.

-Expected Result:
Form fields should be marked as required.

**Comment by success-together** [comment]
Fixed
