### ISSUE TITLE
B#12-Booing Landing page | Inconsistent text Spacing for "Sign up" button

### ISSUE THREAD

**Issue by horizonvert1027** [success-together/Booing-frontend#13]
-Current Behavior:
Notice the inconsistent spacing between the text label for the word SIGN & UP at sign up button 

-App Version
Booing version 2

-Device Tested
• Realme 08, Android v13
• Samsung Galaxy A12, Android v12
• Samsung Galaxy A11, Android v12
• HUAWEI nova 3i v 9
• Vivo 1811, Android v8
• Oppo A83, Android v7

-Steps to Reproduce
1. Launch the ""Booing"" App
2. Verify the text label for Sign up button 

-Expected Result:
The text label "Sign up" should have spacing between each word and the spacing should be consistent in each "sign up "text label button

**Comment by success-together** [comment]
fixed
