### ISSUE TITLE
IssueLive#01-App is being rotated from portrait to landscape.

### ISSUE THREAD

**Issue by horizonvert1027** [success-together/Booing-frontend#2]
## Current Behavior:
Notice that the app is able to be rotated into landscape view.
## App Version:
Booing version 2.0 (from Play Store)
## Device Tested:
All android devices

![landscape-view](https://github.com/oleksandr-harvart/Booing-frontend/assets/117667761/88bad022-ff6c-4763-8ce0-e64825cea1f0)

## Steps to Reproduce:
1 Launch the app.
2. Log in.
3. Rotate your device to a landscape view, make sure that the rotate screen is enabled.
4. Verify that UI/UX is not being loaded in the landcape view and most of the assets and app functionality is not as smooth as when the app is fixed in the portrait view.
## Expected Result
The app should be fixed to a portrait view for a smoother navigation and a better UX/UI. Most of the assets are not being viewed properly on a landscape view and navigating the app on a landscape view is not actually user-friendly.

**Comment by success-together** [comment]
app don't need landscape.
so disabled.

**Comment by horizonvert1027** [comment]
ok, close the issue
