### ISSUE TITLE
IssueLive#02-Logo disappears when rotating the screen from portrait to landscape.

### ISSUE THREAD

**Issue by horizonvert1027** [success-together/Booing-frontend#3]
## Current Behavior:
Notice that when rotating the screen from portrait to a lanscape view, the Booing logo disapppears.

## App Version:
"Booing version 2.0 (from Play Store)"

## Device Tested:
All android devices

<img src="https://github.com/oleksandr-harvart/Booing-frontend/assets/117667761/0ca1fd7c-5639-4a11-a0ec-a2b958b21da3" width="200">

## Steps to Reproduce:
1. Launch the app.
2. Rotate your device.
3. Verify that the logo disappears when the screen gets rotated into a landscape view.

## Expected Result
The app would be better if fixed to a portrait view and the logo should not disappear.

**Comment by success-together** [comment]
It's same [IssueLIve#2](https://github.com/success-together/Booing-frontend/issues/2#top)
landscape was disabled
